Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4711015Z FAILED development/tests/unit/automation/test_http_server.py::test_health_endpoint_returns_daemon_health - AttributeError: 'MockDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4711509Z FAILED development/tests/unit/automation/test_http_server.py::test_metrics_endpoint_returns_prometheus_format - AttributeError: 'MockDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4712002Z FAILED development/tests/unit/automation/test_http_server.py::test_health_endpoint_handles_daemon_error - AttributeError: 'FailingDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4712484Z FAILED development/tests/unit/automation/test_http_server.py::test_metrics_endpoint_handles_daemon_error - AttributeError: 'FailingDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4712920Z FAILED development/tests/unit/automation/test_http_server.py::test_unknown_route_returns_404 - AttributeError: 'MockDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4713592Z FAILED development/tests/unit/automation/test_http_server.py::test_health_endpoint_cors_headers - AttributeError: 'MockDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4714035Z FAILED development/tests/unit/automation/test_http_server.py::test_root_endpoint_returns_info - AttributeError: 'MockDaemon' object has no attribute 'youtube_handler'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4730302Z FAILED development/tests/unit/automation/test_youtube_handler_transcript_integration.py::TestYouTubeHandlerTranscriptIntegration::test_handler_generates_transcript_wikilink - AttributeError: 'NoneType' object has no attribute 'startswith'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4733266Z FAILED development/tests/unit/cli/test_terminal_dashboard_metrics.py::TestTerminalDashboardMetricsDisplay::test_dashboard_can_create_metrics_display_formatter - AttributeError: module 'src.cli.terminal_dashboard' has no attribute 'MetricsStorage'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4733957Z FAILED development/tests/unit/cli/test_terminal_dashboard_metrics.py::TestTerminalDashboardMetricsDisplay::test_dashboard_formatter_displays_counter_metrics - AttributeError: module 'src.cli.terminal_dashboard' has no attribute 'MetricsStorage'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4734641Z FAILED development/tests/unit/cli/test_terminal_dashboard_metrics.py::TestTerminalDashboardMetricsDisplay::test_dashboard_formatter_displays_gauge_metrics - AttributeError: module 'src.cli.terminal_dashboard' has no attribute 'MetricsStorage'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4735294Z FAILED development/tests/unit/cli/test_terminal_dashboard_metrics.py::TestMetricsIntegrationWithDashboard::test_dashboard_handles_empty_metrics - AttributeError: module 'src.cli.terminal_dashboard' has no attribute 'MetricsStorage'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4744647Z FAILED development/tests/unit/test_advanced_tag_enhancement_cli.py::TestCLIProgressReporter::test_completion_reporting - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4745672Z FAILED development/tests/unit/test_advanced_tag_enhancement_cli.py::TestCLIProgressReporter::test_progress_updates_during_processing - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4746537Z FAILED development/tests/unit/test_advanced_tag_enhancement_cli.py::TestEnhancementCommand::test_command_validation - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4754837Z FAILED development/tests/unit/test_cli_safe_workflow_utils.py::TestCLIPerformanceReporter::test_benchmark_processing_performance_fails - Failed: DID NOT RAISE (<class 'ImportError'>, <class 'AttributeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4755987Z FAILED development/tests/unit/test_cli_safe_workflow_utils.py::TestCLIIntegrityMonitor::test_export_integrity_report_fails - Failed: DID NOT RAISE (<class 'ImportError'>, <class 'AttributeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4756857Z FAILED development/tests/unit/test_cli_safe_workflow_utils.py::TestCLIBatchProcessor::test_batch_process_with_progress_fails - Failed: DID NOT RAISE (<class 'ImportError'>, <class 'AttributeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4757406Z FAILED development/tests/unit/test_cli_safe_workflow_utils.py::TestCLIBatchProcessor::test_optimize_batch_size_fails - Failed: DID NOT RAISE (<class 'ImportError'>, <class 'AttributeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4775336Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestEnhancedSuggestionEngine::test_semantic_domain_mapping_enhancement - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4775846Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestQualityScoringRecalibrator::test_contextual_quality_assessment - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4776345Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestQualityScoringRecalibrator::test_false_positive_reduction - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4778850Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestContextualIntelligenceProcessor::test_domain_context_understanding - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4780210Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestContextualIntelligenceProcessor::test_relationship_based_suggestions - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4780742Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestInteractiveWorkflowIntegrator::test_analytics_dashboard_integration - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4781861Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestInteractiveWorkflowIntegrator::test_user_feedback_collection_integration - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4782387Z FAILED development/tests/unit/test_enhanced_ai_features_tdd_iteration_5.py::TestInteractiveWorkflowIntegrator::test_weekly_review_integration - AssertionError: AttributeError not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4786554Z FAILED development/tests/unit/test_enhanced_ai_tag_cleanup_deployment.py::TestTagPollutionPrevention::test_ai_tag_generation_sanitization - AssertionError: (<class 'ImportError'>, <class 'AttributeError'>) not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4787138Z FAILED development/tests/unit/test_enhanced_ai_tag_cleanup_deployment.py::TestTagPollutionPrevention::test_template_tag_sanitization - AssertionError: (<class 'ImportError'>, <class 'AttributeError'>) not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4787810Z FAILED development/tests/unit/test_enhanced_ai_tag_cleanup_deployment.py::TestTagPollutionPrevention::test_weekly_review_tag_sanitization - AssertionError: (<class 'ImportError'>, <class 'AttributeError'>) not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4788445Z FAILED development/tests/unit/test_enhanced_ai_tag_cleanup_deployment.py::TestCleanupDeploymentIntegration::test_performance_monitoring_integration - AssertionError: (<class 'ImportError'>, <class 'AttributeError'>) not raised
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4801700Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_batch_processing_performance_under_10_minutes_target - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_batch_with_performance_tracking'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4802457Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_comprehensive_error_recovery_with_rollback - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'get_recovery_status'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4803292Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_daily_note_ocr_text_organization_and_structure - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'organize_ocr_text_by_timestamp'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4804103Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_daily_note_smart_link_integration_preparation - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'prepare_for_smart_link_integration'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4804895Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_memory_usage_optimization_during_batch_processing - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_with_memory_monitoring'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4806236Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_ocr_quality_assessment_and_confidence_scoring - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_with_quality_assessment'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4807097Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_partial_failure_handling_with_continuation - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_with_partial_failure_handling'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4807895Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_progress_reporting_accuracy_and_eta_calculation - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_with_progress_reporting'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4808684Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_real_daily_note_generation_with_yaml_frontmatter - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'generate_daily_note_with_images'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4809518Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_real_file_accessibility_and_permissions - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'validate_file_accessibility'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4810258Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_real_llama_vision_ocr_integration - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_screenshots_with_ocr'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4812309Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_real_onedrive_sync_status_validation - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'check_onedrive_sync_status'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4813059Z FAILED development/tests/unit/test_evening_screenshot_real_data_tdd_3.py::TestEveningScreenshotRealDataProcessingTDD3::test_user_guidance_for_common_error_scenarios - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'generate_user_guidance'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4856792Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_contextual_filename_generation_from_ocr_content - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'generate_contextual_filename'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4857678Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_enhanced_progress_reporting_individual_creation - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_with_individual_progress_reporting'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4858429Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_fallback_description_strategies - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'generate_fallback_description'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4859850Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_individual_capture_note_generation_core_functionality - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'generate_individual_capture_notes'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4860665Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_individual_screenshot_error_handling_recovery - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_individual_with_error_recovery'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4861453Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_intelligent_description_extraction_from_content - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'extract_intelligent_description'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4862258Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_optimized_individual_processing_pipeline - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'process_screenshots_individually_optimized'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4863035Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_rich_ocr_context_analysis_structure - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'analyze_screenshot_with_rich_context'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4863878Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_smart_link_integration_for_individual_notes - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'suggest_smart_links_for_individual_note'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4864667Z FAILED development/tests/unit/test_individual_screenshot_processing_tdd_5.py::TestIndividualScreenshotProcessingTDD5::test_template_based_individual_note_structure - AttributeError: 'EveningScreenshotProcessor' object has no attribute 'generate_template_based_note_content'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4868702Z FAILED development/tests/unit/test_safe_image_processor.py::TestSafeImageProcessorRedPhase::test_concurrent_processing_safety_fails - Failed: DID NOT RAISE (<class 'AttributeError'>, <class 'TypeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4869309Z FAILED development/tests/unit/test_safe_image_processor.py::TestSafeImageProcessorRedPhase::test_backup_session_lifecycle_fails - Failed: DID NOT RAISE (<class 'ImportError'>, <class 'AttributeError'>, <class 'TypeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4869858Z FAILED development/tests/unit/test_safe_image_processor.py::TestSafeImageProcessorRedPhase::test_backup_integrity_validation_fails - Failed: DID NOT RAISE (<class 'AttributeError'>, <class 'TypeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4870473Z FAILED development/tests/unit/test_safe_image_processor.py::TestSafeImageProcessorRedPhase::test_processing_result_structure_fails - Failed: DID NOT RAISE (<class 'ImportError'>, <class 'AttributeError'>, <class 'TypeError'>)
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4920045Z FAILED development/tests/unit/test_youtube_transcript_fetcher.py::TestYouTubeTranscriptFetcherBasicFunctionality::test_fetch_valid_video_transcript - AttributeError: 'YouTubeTranscriptApi' object has no attribute 'list'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4920862Z FAILED development/tests/unit/test_youtube_transcript_fetcher.py::TestYouTubeTranscriptFetcherBasicFunctionality::test_fetch_video_without_transcript - AttributeError: <youtube_transcript_api._api.YouTubeTranscriptApi object at 0x7fb5234bc7d0> does not have the attribute 'list'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4921707Z FAILED development/tests/unit/test_youtube_transcript_fetcher.py::TestYouTubeTranscriptFetcherBasicFunctionality::test_fetch_manual_vs_auto_transcript_preference - AttributeError: <youtube_transcript_api._api.YouTubeTranscriptApi object at 0x7fb4a2c12650> does not have the attribute 'list'
Lint & Test (Ubuntu)	Run unit tests	2025-10-29T23:34:04.4923644Z FAILED development/tests/unit/test_youtube_transcript_fetcher.py::TestYouTubeTranscriptFetcherErrorHandling::test_handle_network_errors - AttributeError: <youtube_transcript_api._api.YouTubeTranscriptApi object at 0x7fb4a3093b50> does not have the attribute 'list'
